### PR TITLE
Updates for mage-post-proc

### PR DESCRIPTION
**Pull request by gipert**
CC @iguinn

### CODE REVIEW

**Comment by oschulz** [comment]
@iguinn good to merge from your side?

**Comment by oschulz** [comment]
This works for you @gipert , right?

**Comment by gipert** [comment]
Not yet unfortunately, we are looking into it.

**Comment by gipert** [comment]
I have now changed it to explicitly install MGDO, MaGe and MPP instead of relying on `installMaGe.py`, hoping that it would fix the issue with `process_L200_hit.py`. The container builds fine, but I'm still getting the same error:

```console
> process_L200_hit.py -o /tmp/test.root l200a-hpge-bulk-2vbb_0028.root
Import mage-post-proc from: /opt/anaconda3/lib/python3.10/site-packages/magepostproc.py
Error in <TInterpreter::AutoParse>: Error parsing payload code for class MPPChannelTagger with content:

#line 1 "libMPPProcessing dictionary payload"


#define _BACKWARD_BACKWARD_WARNING_H
// Inline headers
#include "MPPTH1Filler.hh"
#include "MPPEnergyHistSmooth.hh"
#include "MPPInputDataPoster.hh"
#include "MPPWindowedDataReader.hh"
#include "MPPChannelTagger.hh"
#include "MPPStepsClusterer.hh"
#include "MPPWFGeneratorSiggen.hh"
#include "MPPL200LightCollectionMap.hh"
#include "MPPL1000LightCollectionMap.hh"
#include "MPPEnergyCalculator.hh"
#include "MPPWindowedDataTreeWriter.hh"
#include "MPPThresholder.hh"
#include "MPPDtHeuristicPsaEmulator.hh"
#include "MPPGeDeadLayerProcessor.hh"
#include "MPPElectronicsConvolutionPZ.hh"
#include "MPPTimeStampGenerator.hh"
#include "MPPSSTCTagger.hh"
#include "MPPSlowPulseTagger.hh"
#include "MPPSensVolWeight.hh"
#include "MPPLArLightCollector.hh"

#undef  _BACKWARD_BACKWARD_WARNING_H

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007f15fe55145a in __GI___wait4 (pid=69, stat_loc=stat_loc
entry=0x7ffc3c4ebea8, options=options
entry=0, usage=usage
entry=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
#1  0x00007f15fe55141b in __GI___waitpid (pid=<optimized out>, stat_loc=stat_loc
entry=0x7ffc3c4ebea8, options=options
entry=0) at ./posix/waitpid.c:38
#2  0x00007f15fe4b7bcb in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:171
#3  0x00007f15efe3e7e4 in TUnixSystem::StackTrace() () from /usr/local/lib/libCore.so.6.28
#4  0x00007f15f0064fc3 in (anonymous namespace)::TExceptionHandlerImp::HandleException(int) () from /usr/local/lib/libcppyy_backend3_10.so.6.28
#5  0x00007f15efe3b999 in TUnixSystem::DispatchSignals(ESignals) () from /usr/local/lib/libCore.so.6.28
#6  <signal handler called>
#7  0x00007f15eaa67e4b in clang::CodeGen::CodeGenFunction::EmitLValueForField(clang::CodeGen::LValue, clang::FieldDecl const*) () from /usr/local/lib/libCling.so
#8  0x00007f15eaa76b24 in clang::CodeGen::CodeGenFunction::EmitMemberExpr(clang::MemberExpr const*) [clone .part.0] () from /usr/local/lib/libCling.so
#9  0x00007f15eaa7b576 in clang::CodeGen::CodeGenFunction::EmitMemberExpr(clang::MemberExpr const*) () from /usr/local/lib/libCling.so
#10 0x00007f15eaa710dd in clang::CodeGen::CodeGenFunction::EmitLValue(clang::Expr const*) () from /usr/local/lib/libCling.so
#11 0x00007f15eaa7684e in clang::CodeGen::CodeGenFunction::EmitCheckedLValue(clang::Expr const*, clang::CodeGen::CodeGenFunction::TypeCheckKind) () from /usr/local/lib/libCling.so
#12 0x00007f15eaa7709f in clang::CodeGen::CodeGenFunction::EmitBinaryOperatorLValue(clang::BinaryOperator const*) [clone .part.0] () from /usr/local/lib/libCling.so
#13 0x00007f15eaa7a1c5 in clang::CodeGen::CodeGenFunction::EmitBinaryOperatorLValue(clang::BinaryOperator const*) () from /usr/local/lib/libCling.so
#14 0x00007f15eaa7132c in clang::CodeGen::CodeGenFunction::EmitLValue(clang::Expr const*) () from /usr/local/lib/libCling.so
#15 0x00007f15eaa716af in clang::CodeGen::CodeGenFunction::EmitIgnoredExpr(clang::Expr const*) () from /usr/local/lib/libCling.so
#16 0x00007f15ea754c6a in clang::CodeGen::CodeGenFunction::EmitStmt(clang::Stmt const*, llvm::ArrayRef<clang::Attr const*>) () from /usr/local/lib/libCling.so
#17 0x00007f15ea755cf2 in clang::CodeGen::CodeGenFunction::EmitCompoundStmtWithoutScope(clang::CompoundStmt const&, bool, clang::CodeGen::AggValueSlot) () from /usr/local/lib/libCling.so
#18 0x00007f15ea756000 in clang::CodeGen::CodeGenFunction::EmitCompoundStmt(clang::CompoundStmt const&, bool, clang::CodeGen::AggValueSlot) () from /usr/local/lib/libCling.so
#19 0x00007f15ea75b74b in clang::CodeGen::CodeGenFunction::EmitSimpleStmt(clang::Stmt const*, llvm::ArrayRef<clang::Attr const*>) () from /usr/local/lib/libCling.so
#20 0x00007f15ea754b96 in clang::CodeGen::CodeGenFunction::EmitStmt(clang::Stmt const*, llvm::ArrayRef<clang::Attr const*>) () from /usr/local/lib/libCling.so
#21 0x00007f15eaa22048 in clang::CodeGen::CodeGenFunction::EmitConstructorBody(clang::CodeGen::FunctionArgList&) () from /usr/local/lib/libCling.so
#22 0x00007f15ea7ba08d in clang::CodeGen::CodeGenFunction::GenerateCode(clang::GlobalDecl, llvm::Function*, clang::CodeGen::CGFunctionInfo const&) () from /usr/local/lib/libCling.so
#23 0x00007f15ea9eb308 in clang::CodeGen::CodeGenModule::codegenCXXStructor(clang::GlobalDecl) () from /usr/local/lib/libCling.so
#24 0x00007f15ea84349e in (anonymous namespace)::ItaniumCXXABI::emitCXXStructor(clang::GlobalDecl) () from /usr/local/lib/libCling.so
#25 0x00007f15ea7f3a0c in clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) () from /usr/local/lib/libCling.so
#26 0x00007f15ea7fb5f2 in clang::CodeGen::CodeGenModule::EmitDeferred() () from /usr/local/lib/libCling.so
#27 0x00007f15ea7fb610 in clang::CodeGen::CodeGenModule::EmitDeferred() () from /usr/local/lib/libCling.so
#28 0x00007f15ea7fb610 in clang::CodeGen::CodeGenModule::EmitDeferred() () from /usr/local/lib/libCling.so
#29 0x00007f15ea7fb610 in clang::CodeGen::CodeGenModule::EmitDeferred() () from /usr/local/lib/libCling.so
#30 0x00007f15ea7fcccc in clang::CodeGen::CodeGenModule::Release() () from /usr/local/lib/libCling.so
#31 0x00007f15ea6fd65a in clang::CodeGeneratorImpl::HandleTranslationUnit(clang::ASTContext&) () from /usr/local/lib/libCling.so
#32 0x00007f15ea5e8dea in cling::IncrementalParser::codeGenTransaction(cling::Transaction*) () from /usr/local/lib/libCling.so
#33 0x00007f15ea5e9105 in cling::IncrementalParser::commitTransaction(llvm::PointerIntPair<cling::Transaction*, 2u, cling::IncrementalParser::EParseResult, llvm::PointerLikeTypeTraits<cling::Transaction*>, llvm::PointerIntPairInfo<cling::Transaction*, 2u, llvm::PointerLikeTypeTraits<cling::Transaction*> > >&, bool) () from /usr/local/lib/libCling.so
#34 0x00007f15ea5577e8 in cling::Interpreter::PushTransactionRAII::~PushTransactionRAII() () from /usr/local/lib/libCling.so
#35 0x00007f15ea56e422 in cling::LookupHelper::findScope(llvm::StringRef, cling::LookupHelper::DiagSetting, clang::Type const**, bool) const () from /usr/local/lib/libCling.so
#36 0x00007f15ea4e5d7d in TClingClassInfo::TClingClassInfo(cling::Interpreter*, char const*, bool) () from /usr/local/lib/libCling.so
#37 0x00007f15ea46e1eb in TCling::GetInterpreterTypeName(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool) () from /usr/local/lib/libCling.so
#38 0x00007f15efddb5c4 in TClass::GetClass(char const*, bool, bool, unsigned long, unsigned long) () from /usr/local/lib/libCore.so.6.28
#39 0x00007f15efe0554b in TProtoClass::FillTClass(TClass*) () from /usr/local/lib/libCore.so.6.28
#40 0x00007f15efde557b in TClass::Init(char const*, short, std::type_info const*, TVirtualIsAProxy*, char const*, char const*, int, int, ClassInfo_t*, bool) () from /usr/local/lib/libCore.so.6.28
#41 0x00007f15efde6cdd in TClass::TClass(char const*, short, std::type_info const&, TVirtualIsAProxy*, char const*, char const*, int, int, bool) () from /usr/local/lib/libCore.so.6.28
#42 0x00007f15efde721d in ROOT::CreateClass(char const*, short, std::type_info const&, TVirtualIsAProxy*, char const*, char const*, int, int) () from /usr/local/lib/libCore.so.6.28
#43 0x00007f15efdf7fe2 in ROOT::TGenericClassInfo::GetClass() () from /usr/local/lib/libCore.so.6.28
#44 0x00007f15c9ad6395 in MPPChannelTagger::Dictionary () at /tmp/build-mage-post-proc-kUs6mA/mage-post-proc/build/Processing/Processing_dict.cxx:831
#45 0x00007f15efddaf52 in TClass::GetClass(char const*, bool, bool, unsigned long, unsigned long) () from /usr/local/lib/libCore.so.6.28
#46 0x00007f15f0074bc1 in Cppyy::GetScope(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /usr/local/lib/libcppyy_backend3_10.so.6.28
#47 0x00007f15f010b4a3 in CPyCppyy::CreateScopeProxy(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, _object*) () from /usr/local/lib/libcppyy3_10.so
#48 0x00007f15f00ec74b in CPyCppyy::meta_getattro(_object*, _object*) () from /usr/local/lib/libcppyy3_10.so
#49 0x0000562edf6b6294 in _PyObject_LookupAttr (result=<synthetic pointer>, name=<optimized out>, v=0x562ee1bd4700) at /usr/local/src/conda/python-3.10.9/Objects/object.c:977
#50 builtin_hasattr_impl (module=<optimized out>, name=<optimized out>, obj=0x562ee1bd4700) at /usr/local/src/conda/python-3.10.9/Python/bltinmodule.c:1163
#51 builtin_hasattr (module=<optimized out>, args=args
entry=0x7f15e97ce890, nargs=<optimized out>) at /usr/local/src/conda/python-3.10.9/Python/clinic/bltinmodule.c.h:424
#52 0x0000562edf6b6184 in cfunction_vectorcall_FASTCALL (func=0x7f15fe0bcf40, args=0x7f15e97ce890, nargsf=<optimized out>, kwnames=<optimized out>) at /usr/local/src/conda/python-3.10.9/Objects/methodobject.c:430
#53 0x0000562edf6a6122 in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=0x7f15e97ce890, callable=0x7f15fe0bcf40, tstate=0x562ee09d2bd0) at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
#54 PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7f15e97ce890, callable=0x7f15fe0bcf40) at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
#55 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, trace_info=0x7ffc3c4f4290, tstate=<optimized out>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
#56 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=0x7f15e97ce710, throwflag=<optimized out>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
#57 0x0000562edf6c1641 in _PyEval_EvalFrame (throwflag=0, f=0x7f15e97ce710, tstate=0x562ee09d2bd0) at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
#58 _PyEval_Vector (kwnames=<optimized out>, argcount=<optimized out>, args=0x7ffc3c4f4400, locals=0x0, con=0x7f15e9867bf0, tstate=0x562ee09d2bd0) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
#59 _PyFunction_Vectorcall (kwnames=<optimized out>, nargsf=<optimized out>, stack=0x7ffc3c4f4400, func=0x7f15e9867be0) at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
#60 _PyObject_VectorcallTstate (kwnames=<optimized out>, nargsf=<optimized out>, args=0x7ffc3c4f4400, callable=0x7f15e9867be0, tstate=0x562ee09d2bd0) at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
#61 method_vectorcall (method=<optimized out>, args=0x7ffc3c4f4408, nargsf=<optimized out>, kwnames=<optimized out>) at /usr/local/src/conda/python-3.10.9/Objects/classobject.c:53
#62 0x0000562edf6eab6f in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=9223372036854775809, args=0x7ffc3c4f4408, callable=0x7f15fdc715c0, tstate=0x562ee09d2bd0) at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
#63 PyObject_CallOneArg (func=0x7f15fdc715c0, arg=<optimized out>) at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:184
#64 0x0000562edf78765e in call_attribute (self=<optimized out>, attr=0x7f15fdc715c0, name=0x7f15c90224c0) at /usr/local/src/conda/python-3.10.9/Objects/typeobject.c:7535
#65 0x0000562edf716378 in slot_tp_getattr_hook (self=0x7f15e97fdbc0, name=0x7f15c90224c0) at /usr/local/src/conda/python-3.10.9/Objects/typeobject.c:7577
#66 0x0000562edf6b63f8 in PyObject_GetAttr (name=0x7f15c90224c0, v=0x7f15e97fdbc0) at /usr/local/src/conda/python-3.10.9/Objects/object.c:932
#67 builtin_getattr (self=<optimized out>, args=args
entry=0x562ee0af6500, nargs=2) at /usr/local/src/conda/python-3.10.9/Python/bltinmodule.c:1106
#68 0x0000562edf6b6184 in cfunction_vectorcall_FASTCALL (func=0x7f15fe0bcea0, args=0x562ee0af6500, nargsf=<optimized out>, kwnames=<optimized out>) at /usr/local/src/conda/python-3.10.9/Objects/methodobject.c:430
#69 0x0000562edf6a6122 in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=0x562ee0af6500, callable=0x7f15fe0bcea0, tstate=0x562ee09d2bd0) at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
#70 PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x562ee0af6500, callable=0x7f15fe0bcea0) at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
#71 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, trace_info=0x7ffc3c4f4660, tstate=<optimized out>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
#72 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=0x562ee0af6390, throwflag=<optimized out>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
#73 0x0000562edf74ea82 in _PyEval_EvalFrame (throwflag=0, f=0x562ee0af6390, tstate=0x562ee09d2bd0) at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
#74 _PyEval_Vector (tstate=0x562ee09d2bd0, con=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kwnames=<optimized out>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
#75 0x0000562edf74e9c7 in PyEval_EvalCode (co=co
entry=0x7f15fdef5f20, globals=globals
entry=0x7f15fdeef840, locals=locals
entry=0x7f15fdeef840) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:1134
#76 0x0000562edf756000 in builtin_exec_impl (module=<optimized out>, locals=0x7f15fdeef840, globals=0x7f15fdeef840, source=0x7f15fdef5f20) at /usr/local/src/conda/python-3.10.9/Python/bltinmodule.c:1056
#77 builtin_exec (module=<optimized out>, args=args
entry=0x7f15fdea4dd8, nargs=<optimized out>) at /usr/local/src/conda/python-3.10.9/Python/clinic/bltinmodule.c.h:371
#78 0x0000562edf6b6184 in cfunction_vectorcall_FASTCALL (func=0x7f15fe0bce00, args=0x7f15fdea4dd8, nargsf=<optimized out>, kwnames=<optimized out>) at /usr/local/src/conda/python-3.10.9/Objects/methodobject.c:430
#79 0x0000562edf6abb7c in do_call_core (kwdict=0x7f15fdeefa00, callargs=0x7f15fdea4dc0, func=0x7f15fe0bce00, trace_info=0x7ffc3c4f4940, tstate=<optimized out>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5915
#80 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=0x7f15fde75b40, throwflag=<optimized out>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4277
#81 0x0000562edf6b5f8f in _PyEval_EvalFrame (throwflag=0, f=0x7f15fde75b40, tstate=0x562ee09d2bd0) at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
#82 _PyEval_Vector (kwnames=<optimized out>, argcount=<optimized out>, args=<optimized out>, locals=0x0, con=0x7f15fe085520, tstate=0x562ee09d2bd0) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
#83 _PyFunction_Vectorcall (func=0x7f15fe085510, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
#84 0x0000562edf6aaafd in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=0x7f15fde656c8, callable=0x7f15fe085510, tstate=0x562ee09d2bd0) at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
#85 PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7f15fde656c8, callable=0x7f15fe085510) at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
#86 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, trace_info=0x7ffc3c4f4b10, tstate=<optimized out>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
#87 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=0x7f15fde65540, throwflag=<optimized out>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4181
#88 0x0000562edf6b5f8f in _PyEval_EvalFrame (throwflag=0, f=0x7f15fde65540, tstate=0x562ee09d2bd0) at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
#89 _PyEval_Vector (kwnames=<optimized out>, argcount=<optimized out>, args=<optimized out>, locals=0x0, con=0x7f15fe1096d0, tstate=0x562ee09d2bd0) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
#90 _PyFunction_Vectorcall (func=0x7f15fe1096c0, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
#91 0x0000562edf6a6525 in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=0x7f15fe0e3610, callable=0x7f15fe1096c0, tstate=0x562ee09d2bd0) at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
#92 PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7f15fe0e3610, callable=0x7f15fe1096c0) at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
#93 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, trace_info=0x7ffc3c4f4ce0, tstate=<optimized out>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
#94 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=0x7f15fe0e3490, throwflag=<optimized out>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4198
#95 0x0000562edf6b5f8f in _PyEval_EvalFrame (throwflag=0, f=0x7f15fe0e3490, tstate=0x562ee09d2bd0) at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
#96 _PyEval_Vector (kwnames=<optimized out>, argcount=<optimized out>, args=<optimized out>, locals=0x0, con=0x7f15fe0860f0, tstate=0x562ee09d2bd0) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
#97 _PyFunction_Vectorcall (func=0x7f15fe0860e0, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
#98 0x0000562edf6a6122 in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=0x7f15fdffebf0, callable=0x7f15fe0860e0, tstate=0x562ee09d2bd0) at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
#99 PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7f15fdffebf0, callable=0x7f15fe0860e0) at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
#100 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, trace_info=0x7ffc3c4f4eb0, tstate=<optimized out>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
#101 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=0x7f15fdffea40, throwflag=<optimized out>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
#102 0x0000562edf6b5f8f in _PyEval_EvalFrame (throwflag=0, f=0x7f15fdffea40, tstate=0x562ee09d2bd0) at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
#103 _PyEval_Vector (kwnames=<optimized out>, argcount=<optimized out>, args=<optimized out>, locals=0x0, con=0x7f15fe0872f0, tstate=0x562ee09d2bd0) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
#104 _PyFunction_Vectorcall (func=0x7f15fe0872e0, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
#105 0x0000562edf6a6122 in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=0x7f15fdffe7d0, callable=0x7f15fe0872e0, tstate=0x562ee09d2bd0) at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
#106 PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7f15fdffe7d0, callable=0x7f15fe0872e0) at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:123
#107 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, trace_info=0x7ffc3c4f5080, tstate=<optimized out>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5891
#108 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=0x7f15fdffe640, throwflag=<optimized out>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:4213
#109 0x0000562edf6b5f8f in _PyEval_EvalFrame (throwflag=0, f=0x7f15fdffe640, tstate=0x562ee09d2bd0) at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
#110 _PyEval_Vector (kwnames=<optimized out>, argcount=<optimized out>, args=<optimized out>, locals=0x0, con=0x7f15fe087380, tstate=0x562ee09d2bd0) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
#111 _PyFunction_Vectorcall (func=0x7f15fe087370, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at /usr/local/src/conda/python-3.10.9/Objects/call.c:342
#112 0x0000562edf6b5734 in _PyObject_VectorcallTstate (kwnames=0x0, nargsf=<optimized out>, args=0x7ffc3c4f51c0, callable=0x7f15fe087370, tstate=0x562ee09d2bd0) at /usr/local/src/conda/python-3.10.9/Include/cpython/abstract.h:114
#113 object_vacall (tstate=0x562ee09d2bd0, base=<optimized out>, callable=0x7f15fe087370, vargs=<optimized out>) at /usr/local/src/conda/python-3.10.9/Objects/call.c:734
#114 0x0000562edf6c3f55 in _PyObject_CallMethodIdObjArgs (obj=<optimized out>, name=<optimized out>) at /usr/local/src/conda/python-3.10.9/Objects/call.c:825
#115 0x0000562edf6c335e in import_find_and_load (abs_name=0x7f15fde305f0, tstate=0x562ee09d2bd0) at /usr/local/src/conda/python-3.10.9/Python/import.c:1522
#116 PyImport_ImportModuleLevelObject (name=0x7f15fde305f0, globals=<optimized out>, locals=<optimized out>, fromlist=0x562edf8ff7c0 <_Py_NoneStruct>, level=0) at /usr/local/src/conda/python-3.10.9/Python/import.c:1623
#117 0x0000562edf6a90f5 in import_name (level=0x7f15fe0240d0, fromlist=0x562edf8ff7c0 <_Py_NoneStruct>, name=0x7f15fde305f0, f=0x7f15fe04dc40, tstate=<optimized out>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:6016
#118 _PyEval_EvalFrameDefault (tstate=<optimized out>, f=0x7f15fe04dc40, throwflag=<optimized out>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:3695
#119 0x0000562edf74ea82 in _PyEval_EvalFrame (throwflag=0, f=0x7f15fe04dc40, tstate=0x562ee09d2bd0) at /usr/local/src/conda/python-3.10.9/Include/internal/pycore_ceval.h:46
#120 _PyEval_Vector (tstate=0x562ee09d2bd0, con=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kwnames=<optimized out>) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:5065
#121 0x0000562edf74e9c7 in PyEval_EvalCode (co=co
entry=0x7f15fdf6b310, globals=globals
entry=0x7f15fdf6e700, locals=locals
entry=0x7f15fdf6e700) at /usr/local/src/conda/python-3.10.9/Python/ceval.c:1134
#122 0x0000562edf78182c in run_eval_code_obj (tstate=0x562ee09d2bd0, co=0x7f15fdf6b310, globals=0x7f15fdf6e700, locals=0x7f15fdf6e700) at /usr/local/src/conda/python-3.10.9/Python/pythonrun.c:1291
#123 0x0000562edf77c704 in run_mod (mod=<optimized out>, filename=<optimized out>, globals=0x7f15fdf6e700, locals=0x7f15fdf6e700, flags=<optimized out>, arena=<optimized out>) at /usr/local/src/conda/python-3.10.9/Python/pythonrun.c:1312
#124 0x0000562edf60d53c in pyrun_file (fp=0x562ee0a31b70, filename=0x7f15fdf7eeb0, start=<optimized out>, globals=0x7f15fdf6e700, locals=0x7f15fdf6e700, closeit=1, flags=0x7ffc3c4f57b8) at /usr/local/src/conda/python-3.10.9/Python/pythonrun.c:1208
#125 0x0000562edf776925 in _PyRun_SimpleFileObject (fp=0x562ee0a31b70, filename=0x7f15fdf7eeb0, closeit=1, flags=0x7ffc3c4f57b8) at /usr/local/src/conda/python-3.10.9/Python/pythonrun.c:456
#126 0x0000562edf7764d3 in _PyRun_AnyFileObject (fp=0x562ee0a31b70, filename=0x7f15fdf7eeb0, closeit=1, flags=0x7ffc3c4f57b8) at /usr/local/src/conda/python-3.10.9/Python/pythonrun.c:90
#127 0x0000562edf7736a9 in pymain_run_file_obj (skip_source_first_line=0, filename=0x7f15fdf7eeb0, program_name=0x7f15fdfbb5b0) at /usr/local/src/conda/python-3.10.9/Modules/main.c:357
#128 pymain_run_file (config=0x562ee09b6e30) at /usr/local/src/conda/python-3.10.9/Modules/main.c:376
#129 pymain_run_python (exitcode=0x7ffc3c4f57b0) at /usr/local/src/conda/python-3.10.9/Modules/main.c:591
#130 Py_RunMain () at /usr/local/src/conda/python-3.10.9/Modules/main.c:670
#131 0x0000562edf741089 in Py_BytesMain (argc=<optimized out>, argv=<optimized out>) at /usr/local/src/conda/python-3.10.9/Modules/main.c:1090
#132 0x00007f15fe490d90 in __libc_start_call_main (main=main
entry=0x562edf741040 <main>, argc=argc
entry=5, argv=argv
entry=0x7ffc3c4f59e8) at ../sysdeps/nptl/libc_start_call_main.h:58
#133 0x00007f15fe490e40 in __libc_start_main_impl (main=0x562edf741040 <main>, argc=5, argv=0x7ffc3c4f59e8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc3c4f59d8) at ../csu/libc-start.c:392
#134 0x0000562edf740f81 in _start ()
===========================================================
```
(the stacktrace is much longer, I have truncated it)

@iguinn I'm  running out of ideas...

**Comment by gipert** [comment]
I have implemented a temporary hack. Merging.

**Pull request merged**
